name       : python-bottle
version    : 0.12.19
release    : 6
source     :
    - https://github.com/bottlepy/bottle/archive/0.12.19.tar.gz : b97277f8e87d452a0aa5fbcd16cd604a189e2cc17fdb2d4eaf6baa732f8d111b
homepage   : https://bottlepy.org/docs/dev/
license    : MIT
component  : programming.python
summary    : Bottle is a fast, simple and lightweight WSGI micro web-framework for Python
description: |
    Bottle is a fast, simple and lightweight WSGI micro web-framework for Python. It offers request dispatching (Routes) with url parameter support, templates, a built-in HTTP Server and adapters for many third party WSGI/HTTP-server and template engines - all in a single file and with no dependencies other than the Python Standard Library.
builddeps  :
    - python-setuptools
setup      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
#check      : |
#    %python_test
#    %python3_test
