name       : python-bottle
version    : 0.12.17
release    : 2
source     :
    - https://github.com/bottlepy/bottle/archive/0.12.17.tar.gz : 7df26ca1789aa0693277c4a86d564524bff03e5d3132d9405946c58739190928
license    : MIT
component  : programming.python
summary    : Bottle is a fast, simple and lightweight WSGI micro web-framework for Python.
description: |
    Bottle is a fast, simple and lightweight WSGI micro web-framework for Python.
builddeps  :
    - python-setuptools
setup      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
#check      : |
#    %python_test
#    %python3_test
