name       : python-bottle
version    : 0.12.21
release    : 8
source     :
    - https://files.pythonhosted.org/packages/source/b/bottle/bottle-0.12.21.tar.gz : 787c61b6cc02b9c229bf2663011fac53dd8fc197f7f8ad2eeede29d888d7887e
homepage   : https://bottlepy.org/docs/dev/
license    : MIT
component  : programming.python
summary    : Bottle is a fast, simple and lightweight WSGI micro web-framework for Python
description: |
    Bottle is a fast, simple and lightweight WSGI micro web-framework for Python. It offers request dispatching (Routes) with url parameter support, templates, a built-in HTTP Server and adapters for many third party WSGI/HTTP-server and template engines - all in a single file and with no dependencies other than the Python Standard Library.
builddeps  :
    - python-setuptools
setup      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
#check      : |
#    %python_test
#    %python3_test
