name       : python-bottle
version    : 0.12.25
release    : 11
source     :
    - https://files.pythonhosted.org/packages/source/b/bottle/bottle-0.12.25.tar.gz : e1a9c94970ae6d710b3fb4526294dfeb86f2cb4a81eff3a4b98dc40fb0e5e021
homepage   : https://bottlepy.org/docs/dev/
license    : MIT
component  : programming.python
summary    : Bottle is a fast, simple and lightweight WSGI micro web-framework for Python
description: |
    Bottle is a fast, simple and lightweight WSGI micro web-framework for Python. It offers request dispatching (Routes) with url parameter support, templates, a built-in HTTP Server and adapters for many third party WSGI/HTTP-server and template engines - all in a single file and with no dependencies other than the Python Standard Library.
builddeps  :
    - python-pytest
setup      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -k 'not test_sendfile'
